### ISSUE TITLE
cargo install is failing

### ISSUE THREAD

**Issue by foxfriends** [dylanowen/mdbook-graphviz#107]
I have a version already installed from before, so I know it's working... but when I try to `cargo install mdbook-graphviz --force` it no longer works, using all the latest (Rust 1.76).

Works when I build from the repo directly though, might just be a dependency version thing and needs a republish

**Comment by tautschnig** [comment]
Note that PRs #104 and #106 are also failing - those try to update some dependencies, but I think what needs to happen is that all of these dependencies are upgraded together (plus some source changes are required).

**Comment by lavajuno** [comment]
It looks like mdbook 0.4.37 bumped pulldown-cmark to 10.0.0, but mdbook-graphviz depends on pulldown-cmark-to-cmark 11.2 (which does not yet support pulldown-cmark 10.0.0). I am able to build it with mdbook 0.4.36 and pulldown-cmark 0.9.6. but as @tautschnig mentioned source changes in pulldown-cmark-to-cmark and here are needed.

**Comment by Alextopher** [comment]
Does installing with the --locked flag fix the problem?

You may also have to stay back on mdbook version 0.4.26 until this crate's dependencies can be updated.

```
cargo install --locked mdbook-graphviz
```

**Comment by GlenDC** [comment]
`0.4.26` was yanked from <crates.io>. I use 0.4.27 instead and together with the locked flag this works like a charm.

**Comment by foxfriends** [comment]
Even 0.4.36 worked for me, it's only the latest 0.4.37 that has issues

**Comment by Cypher1** [comment]
Should be fixed in https://github.com/dylanowen/mdbook-graphviz/pull/116

Just need a new release to go out.

**Comment by tautschnig** [comment]
Confirming that this works fine now (https://github.com/model-checking/kani/pull/3136 demonstrates it). Thank you!

**Comment by GlenDC** [comment]
Can confirm as well, updated to latest together with `mdbook` in https://github.com/plabayo/rama/commit/ff5c4e52940de1d7fd75dc7673568849ee8b6ebc, and it builds fine both in CI and on my dev machine.
