### ISSUE TITLE
mdBook 0.4.x compatibility

### ISSUE THREAD

**Issue by Nainterceptor** [dylanowen/mdbook-graphviz#3]
Hello, 

Is it planned to release a version compatible with mdBook 0.4.x ?

Best regards,
Gaël

**Comment by Nainterceptor** [comment]
Yep, done ! Thx

**Comment by oberien** [comment]
Actually no new mdbook-graphviz version has been published with mdbook 0.4.x support. @dylanowen Could you please make a new release?
