### ISSUE TITLE
allow rendering included files

### ISSUE THREAD

**Issue by flokli** [dylanowen/mdbook-graphviz#31]
I have an external process creating a `.gv` file, and I want to use the `{{#include path/to.gv}}` directive to include the file:

```dot process
{{#include path/to.gv}}
```

This fails, as apparently the include directive is interpreted as raw graphviz code:

```
2022-04-27 11:34:10 [INFO] (mdbook::book): Book building has started
Warning: The graphviz plugin was built against version 0.4.15 of mdbook, but we're being called from version 0.4.17
Error: <stdin>: syntax error in line 1 near '{'
Error response from Graphviz
2022-04-27 11:34:10 [ERROR] (mdbook::utils): Error: The "graphviz" preprocessor exited unsuccessfully with exit status: 1 status
```

It would be nice if this was supported, or another way to embed a rendered `.gv` into mdbook.

**Comment by dylanowen** [comment]
I haven't played around with included files yet but was this with something like:
~~~
```dot process
{{#include path/to.gv}}
```
~~~
?

**Comment by dylanowen** [comment]
Also maybe <https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html?highlight=preprocessors#require-a-certain-order> could help

**Comment by flokli** [comment]
> I haven't played around with included files yet but was this with something like:
> 
> ```
> ```dot process
> {{#include path/to.gv}}
> ```
> ```
> 
> ?

Yeah, sorry, that's what I wanted to write, but github did interpret it.

**Comment by dylanowen** [comment]
Gotcha, yeah you have to layer the code block deliminators https://github.com/dylanowen/mdbook-graphviz/blob/master/Readme.md?plain=1#L34

**Comment by flokli** [comment]
@dylanowen yes, you were right - using the preprocessors and their orders was the right fix. I opened https://github.com/dylanowen/mdbook-graphviz/pull/33, which adds a section into the Readme explaining this. PTAL!
