### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by matthiasbeyer** [dylanowen/mdbook-graphviz#40]
As far as I can see, there was no release for some time.

Can we get one? For updated dependencies at least? :smile:

**Comment by saona-raimundo** [comment]
I had problems installing the current published version. While running
```
cargo install mdbook-graphviz
```
there is an error compiling mdbook v0.4.15, a dependency of the published version.

My fix was installing it from git
```
cargo install mdbook-graphviz --git https://github.com/dylanowen/mdbook-graphviz
```
